import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, push, set, update, remove, onValue, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
import { firebaseConfig } from "/firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),database=getDatabase(app),$=(id)=>document.getElementById(id);let activeUser=null,reminders=[],reminderFilter="pending",editingReminderId=null;
function occupationText(profile){const labels={profesional:"Profesional",estudiante:"Estudiante",desempleado:"Desempleado"};const base=labels[profile.occupation]||profile.occupation||"Sin ocupación";return profile.occupationDetail?`${base} · ${profile.occupationDetail}`:base}
function pillWidth(text){const probe=document.createElement("span"),target=$("pillValue");probe.textContent=text;probe.style.cssText=`position:absolute;visibility:hidden;white-space:nowrap;font:${getComputedStyle(target).font}`;document.body.appendChild(probe);const width=Math.min(probe.getBoundingClientRect().width+38,480,window.innerWidth-92);probe.remove();return Math.max(width,72)}
function setPillValue(text,animate=true){const target=$("pillValue"),pill=$("userPill");pill.style.width=`${pillWidth(text)}px`;if(!animate){target.textContent=text;return}target.classList.add("leaving");window.setTimeout(()=>{target.textContent=text;target.classList.remove("leaving");target.classList.add("entering");window.setTimeout(()=>target.classList.remove("entering"),350)},180)}
function startPillAnimation(values){let index=0;setPillValue(values[0],false);if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;window.setInterval(()=>{index=(index+1)%values.length;setPillValue(values[index])},2600)}
function fillUser(user,profile){const name=profile.fullName||user.displayName||"Usuario",email=profile.email||user.email||"Sin email";$("hubUserName").textContent=name;startPillAnimation([name,email,occupationText(profile)]);if(user.photoURL){const image=document.createElement("img");image.src=user.photoURL;image.alt=name;image.referrerPolicy="no-referrer";$("hubAvatar").replaceChildren(image)}else $("hubAvatar").textContent=name.slice(0,2).toUpperCase()}
onAuthStateChanged(auth,async(user)=>{if(!user){window.location.replace("/study/panel");return}try{const snapshot=await get(ref(database,`users/${user.uid}/profile`)),profile=snapshot.val();if(!profile?.completed){window.location.replace("/study/panel/ingreso");return}activeUser=user;fillUser(user,profile);listenReminders();$("hubLoading").classList.add("hidden");$("dashboard").classList.remove("hidden")}catch(error){console.error(error);window.location.replace("/study/panel/ingreso")}});
function closeMenu(){$("sidebar").classList.remove("open");$("sidebarOverlay").classList.remove("visible")}
$("collapseButton").addEventListener("click",()=>{$("sidebar").classList.add("fully-hidden");document.querySelector(".hub-main").classList.add("sidebar-hidden");$("sidebarOpener").classList.add("visible")});
$("sidebarOpenButton").addEventListener("click",()=>{$("sidebar").classList.remove("fully-hidden");document.querySelector(".hub-main").classList.remove("sidebar-hidden");$("sidebarOpener").classList.remove("visible")});
document.querySelectorAll(".section-toggle").forEach(toggle=>toggle.addEventListener("click",()=>{const section=$(toggle.dataset.target),hidden=section.classList.toggle("options-hidden"),name=toggle.closest(".sidebar-menu-head").querySelector("span").textContent;toggle.classList.toggle("closed",hidden);toggle.setAttribute("aria-expanded",String(!hidden));toggle.setAttribute("aria-label",`${hidden?"Mostrar":"Ocultar"} sección ${name}`)}));
function setTheme(dark){document.body.classList.toggle("dark-theme",dark);localStorage.setItem("studyhub-theme",dark?"dark":"light");document.querySelectorAll(".theme-toggle").forEach(button=>{button.setAttribute("aria-label",dark?"Activar tema claro":"Activar tema oscuro");button.querySelector("i").className=dark?"fa-regular fa-sun":"fa-regular fa-moon"})}
setTheme(localStorage.getItem("studyhub-theme")==="dark");
document.querySelectorAll(".theme-toggle").forEach(button=>button.addEventListener("click",()=>setTheme(!document.body.classList.contains("dark-theme"))));
$("mobileMenuButton").addEventListener("click",()=>{$("sidebar").classList.add("open");$("sidebarOverlay").classList.add("visible")});$("sidebarOverlay").addEventListener("click",closeMenu);
document.querySelectorAll(".nav-item").forEach(item=>item.addEventListener("click",()=>{document.querySelector(".nav-item.active")?.classList.remove("active");item.classList.add("active");const name=item.querySelector("span").textContent,isReminders=name==="Recordatorios";$("remindersView").classList.toggle("hidden",!isReminders);$("genericView").classList.toggle("hidden",isReminders);if(!isReminders){$("sectionTitle").textContent=name;document.querySelector(".placeholder-icon i").className=item.querySelector("i").className}closeMenu()}));
$("hubLogout").addEventListener("click",async()=>{await signOut(auth);window.location.replace("/")});

function reminderPath(id=""){return `users/${activeUser.uid}/reminders${id?`/${id}`:""}`}
function listenReminders(){onValue(ref(database,reminderPath()),snapshot=>{const data=snapshot.val()||{};reminders=Object.entries(data).map(([id,value])=>({id,...value})).sort((a,b)=>`${a.date||"9999-12-31"} ${a.time||"23:59"}`.localeCompare(`${b.date||"9999-12-31"} ${b.time||"23:59"}`));moveExpiredToTrash();renderReminders()})}
function moveExpiredToTrash(){const limit=Date.now()-7*24*60*60*1000;reminders.filter(item=>item.completed&&!item.deleted&&typeof item.completedAt==="number"&&item.completedAt<=limit).forEach(item=>update(ref(database,reminderPath(item.id)),{deleted:true,deletedAt:serverTimestamp()}))}
function escapeHTML(value=""){const node=document.createElement("div");node.textContent=value;return node.innerHTML}
function parseReminderItems(value){return value.split("\n").filter(line=>line.trim()).slice(0,30).map(line=>{const spaces=line.match(/^[\t ]*/)[0],level=spaces.includes("\t")||spaces.length>=2?1:0,text=line.trim().replace(/^[-•]\s*/,"");return{text,level,done:false}}).filter(item=>item.text)}
function serializeReminderItems(items=[]){return(Array.isArray(items)?items:[]).map(item=>`${item.level?"  ":""}${item.text}`).join("\n")}
function formatReminderDate(date,time){if(!date)return time?`Sin fecha · ${time}`:"Sin fecha ni hora";const parsed=new Date(`${date}T${time||"12:00"}`),today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);let label=parsed.toLocaleDateString("es-AR",{day:"numeric",month:"short"});if(parsed.toDateString()===today.toDateString())label="Hoy";else if(parsed.toDateString()===tomorrow.toDateString())label="Mañana";return `${label}${time?` · ${time}`:""}`}
function isOverdue(item){if(item.completed||!item.date)return false;const end=item.time||"23:59";return new Date(`${item.date}T${end}`)<new Date()}
function renderReminders(){const active=reminders.filter(item=>!item.deleted),trash=reminders.filter(item=>item.deleted),pending=active.filter(item=>!item.completed).length,completed=active.length-pending;$("pendingCount").textContent=pending;$("completedCount").textContent=completed;$("trashCount").textContent=trash.length;const visible=reminderFilter==="trash"?trash:active.filter(item=>reminderFilter==="all"||(reminderFilter==="completed"?item.completed:!item.completed));$("clearReminders").classList.toggle("hidden",reminderFilter!=="completed"&&reminderFilter!=="trash");$("clearReminders").textContent=reminderFilter==="trash"?"Vaciar papelera":"Borrar completados";$("remindersList").innerHTML=visible.map(item=>{const items=Array.isArray(item.items)?item.items:[],subitems=items.length?`<div class="reminder-subitems">${items.map((sub,index)=>item.deleted?`<div class="subitem level-${sub.level||0} ${sub.done?"done":""}"><span class="sub-check"><i class="fa-solid fa-check"></i></span><span>${escapeHTML(sub.text)}</span></div>`:`<button class="subitem level-${sub.level||0} ${sub.done?"done":""}" data-action="subtoggle" data-id="${item.id}" data-index="${index}"><span class="sub-check"><i class="fa-solid fa-check"></i></span><span>${escapeHTML(sub.text)}</span></button>`).join("")}</div>`:"";return`<article class="reminder-card ${item.completed?"completed":""} ${item.deleted?"deleted":""} ${isOverdue(item)?"overdue":""}">${item.deleted?'<span class="deleted-marker"><i class="fa-regular fa-trash-can"></i></span>':`<button class="complete-reminder" data-action="toggle" data-id="${item.id}" aria-label="${item.completed?"Marcar pendiente":"Marcar completado"}"><i class="fa-solid fa-check"></i></button>`}<div class="reminder-info"><h3>${escapeHTML(item.title)}</h3>${item.description?`<p>${escapeHTML(item.description)}</p>`:""}${subitems}<span class="reminder-date"><i class="fa-regular fa-clock"></i>${isOverdue(item)?"Vencido · ":""}${formatReminderDate(item.date,item.time)}</span></div><div class="reminder-actions">${item.deleted?"":`<button class="edit-reminder" data-action="edit" data-id="${item.id}" aria-label="Editar"><i class="fa-regular fa-pen-to-square"></i></button>`}<button class="delete-reminder ${item.deleted?"restore-reminder":""}" data-action="${item.deleted?"restore":"delete"}" data-id="${item.id}" aria-label="${item.deleted?"Recuperar":"Eliminar"}"><i class="fa-solid ${item.deleted?"fa-rotate-left":"fa-trash-can"}"></i></button></div></article>`}).join("");$("reminderEmpty").classList.toggle("hidden",visible.length>0)}
function toggleForm(show,item=null){const form=$("reminderForm");if(show){editingReminderId=item?.id||null;$("reminderFormTitle").textContent=item?"Editar recordatorio":"Nuevo recordatorio";$("saveReminder").textContent=item?"Guardar cambios":"Guardar recordatorio";$("reminderTitle").value=item?.title||"";$("reminderDate").value=item?.date||"";$("reminderTime").value=item?.time||"";$("reminderDescription").value=item?.description||"";$("reminderItems").value=serializeReminderItems(item?.items);form.classList.add("open");setTimeout(()=>$("reminderTitle").focus(),180)}else{form.classList.remove("open");window.setTimeout(()=>{form.reset();editingReminderId=null;$("reminderError").classList.add("hidden")},330)}}
$("newReminderButton").addEventListener("click",()=>toggleForm(true));$("closeReminderForm").addEventListener("click",()=>toggleForm(false));$("cancelReminder").addEventListener("click",()=>toggleForm(false));
$("reminderForm").addEventListener("submit",async event=>{event.preventDefault();const title=$("reminderTitle").value.trim(),date=$("reminderDate").value,time=$("reminderTime").value,description=$("reminderDescription").value.trim(),parsedItems=parseReminderItems($("reminderItems").value),previous=reminders.find(item=>item.id===editingReminderId),oldItems=Array.isArray(previous?.items)?previous.items:[],items=parsedItems.map((item,index)=>({...item,done:oldItems[index]?.text===item.text&&Number(oldItems[index]?.level||0)===item.level?Boolean(oldItems[index].done):false}));if(!title){$("reminderError").textContent="Escribe un título para el recordatorio.";$("reminderError").classList.remove("hidden");return}$("saveReminder").disabled=true;try{if(editingReminderId)await update(ref(database,reminderPath(editingReminderId)),{title,date,time,description,items,updatedAt:serverTimestamp()});else{const itemRef=push(ref(database,reminderPath()));await set(itemRef,{title,date,time,description,items,completed:false,deleted:false,createdAt:serverTimestamp()})}toggleForm(false)}catch(error){console.error(error);$("reminderError").textContent="No se pudo guardar el recordatorio.";$("reminderError").classList.remove("hidden")}finally{$("saveReminder").disabled=false}});
$("reminderFilters").addEventListener("click",event=>{const button=event.target.closest("button[data-filter]");if(!button)return;document.querySelector(".reminder-filters .active")?.classList.remove("active");button.classList.add("active");reminderFilter=button.dataset.filter;renderReminders()});
$("remindersList").addEventListener("click",async event=>{const button=event.target.closest("button[data-action]");if(!button)return;const item=reminders.find(reminder=>reminder.id===button.dataset.id);if(!item)return;if(button.dataset.action==="edit")toggleForm(true,item);else if(button.dataset.action==="toggle")await update(ref(database,reminderPath(item.id)),{completed:!item.completed,completedAt:!item.completed?serverTimestamp():null});else if(button.dataset.action==="delete")await update(ref(database,reminderPath(item.id)),{deleted:true,deletedAt:serverTimestamp()});else if(button.dataset.action==="restore")await update(ref(database,reminderPath(item.id)),{deleted:false,deletedAt:null,completed:false,completedAt:null});else if(button.dataset.action==="subtoggle"){const index=Number(button.dataset.index),items=Array.isArray(item.items)?item.items:[];if(items[index])await update(ref(database,`${reminderPath(item.id)}/items/${index}`),{done:!items[index].done})}})
$("clearReminders").addEventListener("click",async()=>{const targets=reminders.filter(item=>reminderFilter==="trash"?item.deleted:item.completed&&!item.deleted);if(!targets.length)return;const message=reminderFilter==="trash"?"¿Vaciar la papelera definitivamente?":"¿Borrar definitivamente todos los completados?";if(!window.confirm(message))return;$("clearReminders").disabled=true;try{await Promise.all(targets.map(item=>remove(ref(database,reminderPath(item.id)))))}finally{$("clearReminders").disabled=false}})
