import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, push, set, update, remove, onValue, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
import { firebaseConfig } from "/firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),database=getDatabase(app),$=(id)=>document.getElementById(id);let activeUser=null,reminders=[],reminderFilter="pending";
function occupationText(profile){const labels={profesional:"Profesional",estudiante:"Estudiante",desempleado:"Desempleado"};const base=labels[profile.occupation]||profile.occupation||"Sin ocupación";return profile.occupationDetail?`${base} · ${profile.occupationDetail}`:base}
function pillWidth(text){const probe=document.createElement("span"),target=$("pillValue");probe.textContent=text;probe.style.cssText=`position:absolute;visibility:hidden;white-space:nowrap;font:${getComputedStyle(target).font}`;document.body.appendChild(probe);const width=Math.min(probe.getBoundingClientRect().width+38,480,window.innerWidth-92);probe.remove();return Math.max(width,72)}
function setPillValue(text,animate=true){const target=$("pillValue"),pill=$("userPill");pill.style.width=`${pillWidth(text)}px`;if(!animate){target.textContent=text;return}target.classList.add("leaving");window.setTimeout(()=>{target.textContent=text;target.classList.remove("leaving");target.classList.add("entering");window.setTimeout(()=>target.classList.remove("entering"),350)},180)}
function startPillAnimation(values){let index=0;setPillValue(values[0],false);if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;window.setInterval(()=>{index=(index+1)%values.length;setPillValue(values[index])},2600)}
function fillUser(user,profile){const name=profile.fullName||user.displayName||"Usuario",email=profile.email||user.email||"Sin email";$("hubUserName").textContent=name;startPillAnimation([name,email,occupationText(profile)]);if(user.photoURL){const image=document.createElement("img");image.src=user.photoURL;image.alt=name;image.referrerPolicy="no-referrer";$("hubAvatar").replaceChildren(image)}else $("hubAvatar").textContent=name.slice(0,2).toUpperCase()}
onAuthStateChanged(auth,async(user)=>{if(!user){window.location.replace("/study/panel");return}try{const snapshot=await get(ref(database,`users/${user.uid}/profile`)),profile=snapshot.val();if(!profile?.completed){window.location.replace("/study/panel/ingreso");return}activeUser=user;fillUser(user,profile);listenReminders();$("hubLoading").classList.add("hidden");$("dashboard").classList.remove("hidden")}catch(error){console.error(error);window.location.replace("/study/panel/ingreso")}});
function closeMenu(){$("sidebar").classList.remove("open");$("sidebarOverlay").classList.remove("visible")}
$("collapseButton").addEventListener("click",()=>{$("sidebar").classList.add("fully-hidden");document.querySelector(".hub-main").classList.add("sidebar-hidden");$("sidebarOpener").classList.add("visible")});
$("sidebarOpenButton").addEventListener("click",()=>{$("sidebar").classList.remove("fully-hidden");document.querySelector(".hub-main").classList.remove("sidebar-hidden");$("sidebarOpener").classList.remove("visible")});
document.querySelectorAll(".section-toggle").forEach(toggle=>toggle.addEventListener("click",()=>{const section=$(toggle.dataset.target),hidden=section.classList.toggle("options-hidden"),name=toggle.closest(".sidebar-menu-head").querySelector("span").textContent;toggle.classList.toggle("closed",hidden);toggle.setAttribute("aria-expanded",String(!hidden));toggle.setAttribute("aria-label",`${hidden?"Mostrar":"Ocultar"} sección ${name}`)}));
function setTheme(dark){document.body.classList.toggle("dark-theme",dark);localStorage.setItem("studyhub-theme",dark?"dark":"light");document.querySelectorAll(".theme-toggle").forEach(button=>{button.setAttribute("aria-label",dark?"Activar tema claro":"Activar tema oscuro");button.querySelector("i").className=dark?"fa-regular fa-sun":"fa-regular fa-moon"})}
setTheme(localStorage.getItem("studyhub-theme")==="dark");
document.querySelectorAll(".theme-toggle").forEach(button=>button.addEventListener("click",()=>setTheme(!document.body.classList.contains("dark-theme"))));
$("mobileMenuButton").addEventListener("click",()=>{$("sidebar").classList.add("open");$("sidebarOverlay").classList.add("visible")});$("sidebarOverlay").addEventListener("click",closeMenu);
document.querySelectorAll(".nav-item").forEach(item=>item.addEventListener("click",()=>{document.querySelector(".nav-item.active")?.classList.remove("active");item.classList.add("active");const name=item.querySelector("span").textContent,isReminders=name==="Recordatorios";$("remindersView").classList.toggle("hidden",!isReminders);$("genericView").classList.toggle("hidden",isReminders);if(!isReminders){$("sectionTitle").textContent=name;document.querySelector(".placeholder-icon i").className=item.querySelector("i").className}closeMenu()}));
$("hubLogout").addEventListener("click",async()=>{await signOut(auth);window.location.replace("/")});

function reminderPath(id=""){return `users/${activeUser.uid}/reminders${id?`/${id}`:""}`}
function listenReminders(){onValue(ref(database,reminderPath()),snapshot=>{const data=snapshot.val()||{};reminders=Object.entries(data).map(([id,value])=>({id,...value})).sort((a,b)=>`${a.date} ${a.time||"23:59"}`.localeCompare(`${b.date} ${b.time||"23:59"}`));renderReminders()})}
function escapeHTML(value=""){const node=document.createElement("div");node.textContent=value;return node.innerHTML}
function formatReminderDate(date,time){const parsed=new Date(`${date}T${time||"12:00"}`),today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);let label=parsed.toLocaleDateString("es-AR",{day:"numeric",month:"short"});if(parsed.toDateString()===today.toDateString())label="Hoy";else if(parsed.toDateString()===tomorrow.toDateString())label="Mañana";return `${label}${time?` · ${time}`:""}`}
function isOverdue(item){if(item.completed)return false;const end=item.time||"23:59";return new Date(`${item.date}T${end}`)<new Date()}
function renderReminders(){const pending=reminders.filter(item=>!item.completed).length,completed=reminders.length-pending;$("pendingCount").textContent=pending;$("completedCount").textContent=completed;const visible=reminders.filter(item=>reminderFilter==="all"||(reminderFilter==="completed"?item.completed:!item.completed));$("remindersList").innerHTML=visible.map(item=>`<article class="reminder-card ${item.completed?"completed":""} ${isOverdue(item)?"overdue":""}"><button class="complete-reminder" data-action="toggle" data-id="${item.id}" aria-label="${item.completed?"Marcar pendiente":"Marcar completado"}"><i class="fa-solid fa-check"></i></button><div class="reminder-info"><h3>${escapeHTML(item.title)}</h3>${item.description?`<p>${escapeHTML(item.description)}</p>`:""}<span class="reminder-date"><i class="fa-regular fa-clock"></i>${isOverdue(item)?"Vencido · ":""}${formatReminderDate(item.date,item.time)}</span></div><button class="delete-reminder" data-action="delete" data-id="${item.id}" aria-label="Eliminar"><i class="fa-regular fa-trash-can"></i></button></article>`).join("");$("reminderEmpty").classList.toggle("hidden",visible.length>0)}
function toggleForm(show){$("reminderForm").classList.toggle("hidden",!show);if(show){$("reminderDate").min=new Date().toISOString().split("T")[0];$("reminderDate").value=$("reminderDate").value||new Date().toISOString().split("T")[0];setTimeout(()=>$("reminderTitle").focus(),50)}else{$("reminderForm").reset();$("reminderError").classList.add("hidden")}}
$("newReminderButton").addEventListener("click",()=>toggleForm(true));$("closeReminderForm").addEventListener("click",()=>toggleForm(false));$("cancelReminder").addEventListener("click",()=>toggleForm(false));
$("reminderForm").addEventListener("submit",async event=>{event.preventDefault();const title=$("reminderTitle").value.trim(),date=$("reminderDate").value,time=$("reminderTime").value,description=$("reminderDescription").value.trim();if(!title||!date){$("reminderError").textContent="Completa el título y la fecha.";$("reminderError").classList.remove("hidden");return}$("saveReminder").disabled=true;try{const itemRef=push(ref(database,reminderPath()));await set(itemRef,{title,date,time,description,completed:false,createdAt:serverTimestamp()});toggleForm(false)}catch(error){console.error(error);$("reminderError").textContent="No se pudo guardar el recordatorio.";$("reminderError").classList.remove("hidden")}finally{$("saveReminder").disabled=false}});
$("reminderFilters").addEventListener("click",event=>{const button=event.target.closest("button[data-filter]");if(!button)return;document.querySelector(".reminder-filters .active")?.classList.remove("active");button.classList.add("active");reminderFilter=button.dataset.filter;renderReminders()});
$("remindersList").addEventListener("click",async event=>{const button=event.target.closest("button[data-action]");if(!button)return;const item=reminders.find(reminder=>reminder.id===button.dataset.id);if(!item)return;if(button.dataset.action==="toggle")await update(ref(database,reminderPath(item.id)),{completed:!item.completed,completedAt:!item.completed?serverTimestamp():null});else if(button.dataset.action==="delete"&&window.confirm("¿Eliminar este recordatorio?"))await remove(ref(database,reminderPath(item.id)))})
