import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { getDatabase, ref, get, push, set, update, remove, onValue, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-database.js";
import { getStorage, ref as storageRef, uploadBytes, uploadBytesResumable, getDownloadURL, deleteObject } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-storage.js";
import { firebaseConfig } from "/firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),database=getDatabase(app),storage=getStorage(app),$=(id)=>document.getElementById(id);let activeUser=null,reminders=[],reminderFilter="pending",editingReminderId=null,calendarEvents=[],editingCalendarEventId=null,selectedEventColor="#3b82f6",driveItems=[],currentFolderId=null,editingDriveItemId=null,editingFileContentId=null,pdfPendingAnnotations=[],filesViewMode="grid";const now=new Date(),RETENTION_MS=7*24*60*60*1000;let calendarDate=new Date(now.getFullYear(),now.getMonth(),1);
function occupationText(profile){const labels={profesional:"Profesional",estudiante:"Estudiante",desempleado:"Desempleado"};const base=labels[profile.occupation]||profile.occupation||"Sin ocupación";return profile.occupationDetail?`${base} · ${profile.occupationDetail}`:base}
function updateWelcomeDate(){const current=new Date(),weekday=current.toLocaleDateString("es-AR",{weekday:"long"}),date=current.toLocaleDateString("es-AR",{day:"numeric",month:"long"});$("welcomeDate").textContent=`${weekday.charAt(0).toUpperCase()+weekday.slice(1)}, ${date}`}
function fillUser(user,profile){const name=profile.fullName||user.displayName||"Usuario",firstName=name.trim().split(/\s+/)[0]||"Usuario";$("hubUserName").textContent=name;$("welcomeName").textContent=firstName;updateWelcomeDate();if(user.photoURL){const image=document.createElement("img");image.src=user.photoURL;image.alt=name;image.referrerPolicy="no-referrer";$("hubAvatar").replaceChildren(image)}else $("hubAvatar").textContent=name.slice(0,2).toUpperCase()}
onAuthStateChanged(auth,async(user)=>{if(!user){window.location.replace("/study/panel");return}try{const snapshot=await get(ref(database,`users/${user.uid}/profile`)),profile=snapshot.val();if(!profile?.completed){window.location.replace("/study/panel/ingreso");return}activeUser=user;fillUser(user,profile);listenReminders();listenCalendarEvents();listenDriveItems();$("hubLoading").classList.add("hidden");$("dashboard").classList.remove("hidden")}catch(error){console.error(error);window.location.replace("/study/panel/ingreso")}});
function closeMenu(){$("sidebar").classList.remove("open");$("sidebarOverlay").classList.remove("visible")}
$("collapseButton").addEventListener("click",()=>{$("sidebar").classList.add("fully-hidden");document.querySelector(".hub-main").classList.add("sidebar-hidden");$("sidebarOpener").classList.add("visible")});
$("sidebarOpenButton").addEventListener("click",()=>{$("sidebar").classList.remove("fully-hidden");document.querySelector(".hub-main").classList.remove("sidebar-hidden");$("sidebarOpener").classList.remove("visible")});
document.querySelectorAll(".section-toggle").forEach(toggle=>toggle.addEventListener("click",()=>{const section=$(toggle.dataset.target),hidden=section.classList.toggle("options-hidden"),name=toggle.closest(".sidebar-menu-head").querySelector("span").textContent;toggle.classList.toggle("closed",hidden);toggle.setAttribute("aria-expanded",String(!hidden));toggle.setAttribute("aria-label",`${hidden?"Mostrar":"Ocultar"} sección ${name}`)}));
function setTheme(dark){document.documentElement.classList.toggle("dark-theme",dark);document.body.classList.toggle("dark-theme",dark);document.documentElement.style.colorScheme=dark?"dark":"light";localStorage.setItem("studyhub-theme",dark?"dark":"light");document.querySelectorAll(".theme-toggle").forEach(button=>{button.setAttribute("aria-label",dark?"Activar tema claro":"Activar tema oscuro");button.setAttribute("title",dark?"Tema claro":"Tema oscuro");button.querySelector("i").className=dark?"fa-regular fa-sun":"fa-regular fa-moon"})}
setTheme(localStorage.getItem("studyhub-theme")==="dark");
document.querySelectorAll(".theme-toggle").forEach(button=>button.addEventListener("click",()=>setTheme(!document.body.classList.contains("dark-theme"))));
$("mobileMenuButton").addEventListener("click",()=>{$("sidebar").classList.add("open");$("sidebarOverlay").classList.add("visible")});$("sidebarOverlay").addEventListener("click",closeMenu);
function showHubSection(name){const isHome=name==="Inicio",isReminders=name==="Recordatorios",isCalendar=name==="Calendario",isFiles=name==="Archivos",isGeneric=!isHome&&!isReminders&&!isCalendar&&!isFiles;$("welcomeView").classList.toggle("hidden",!isHome);$("remindersView").classList.toggle("hidden",!isReminders);$("calendarView").classList.toggle("hidden",!isCalendar);$("filesView").classList.toggle("hidden",!isFiles);$("genericView").classList.toggle("hidden",!isGeneric);document.querySelectorAll(".nav-item").forEach(item=>item.classList.toggle("active",(item.dataset.section||item.querySelector("span")?.textContent)===name));if(isCalendar)renderCalendar();else if(isFiles)renderDriveItems();else if(isGeneric){$("sectionTitle").textContent=name;const source=document.querySelector(`.nav-item[data-section="${name}"] i`);if(source)document.querySelector(".placeholder-icon i").className=source.className}closeMenu()}
document.querySelectorAll(".nav-item").forEach(item=>item.addEventListener("click",()=>showHubSection(item.dataset.section||item.querySelector("span").textContent)));
document.querySelectorAll("[data-go]").forEach(button=>button.addEventListener("click",()=>showHubSection(button.dataset.go)));
$("hubLogout").addEventListener("click",async()=>{await signOut(auth);window.location.replace("/")});

function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function dateKey(date){const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,"0"),day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}
function updateCalendarClock(){const current=new Date(),longDate=current.toLocaleDateString("es-AR",{day:"numeric",month:"long"}),shortDate=current.toLocaleDateString("es-AR",{day:"2-digit",month:"2-digit",year:"2-digit"}),time=current.toLocaleTimeString("es-AR",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"});$("calendarTodayLabel").textContent=`${longDate}, ${shortDate} -- ${time} PM`}
function calendarEventPath(id=""){return `users/${activeUser.uid}/calendarEvents${id?`/${id}`:""}`}
function isExpiredCalendarEvent(item,referenceTime=Date.now()){if(!item?.date)return false;const dayEnd=new Date(`${item.date}T23:59:59.999`).getTime();return Number.isFinite(dayEnd)&&dayEnd+RETENTION_MS<=referenceTime}
function cleanupExpiredCalendarEvents(items){const expired=items.filter(item=>isExpiredCalendarEvent(item));if(!expired.length)return;Promise.all(expired.map(item=>remove(ref(database,calendarEventPath(item.id))))).catch(error=>console.error("No se pudieron limpiar actividades antiguas del calendario.",error))}
function listenCalendarEvents(){onValue(ref(database,calendarEventPath()),snapshot=>{const data=snapshot.val()||{},allEvents=Object.entries(data).map(([id,value])=>({id,...value}));calendarEvents=allEvents.filter(item=>!isExpiredCalendarEvent(item)).sort((a,b)=>`${a.date} ${a.time||"23:59"}`.localeCompare(`${b.date} ${b.time||"23:59"}`));const todayKey=dateKey(new Date()),upcoming=calendarEvents.filter(item=>item.date>=todayKey).length;if($("welcomeEventCount"))$("welcomeEventCount").textContent=upcoming;cleanupExpiredCalendarEvents(allEvents);renderCalendar()})}
function renderCalendar(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,days=new Date(year,month+1,0).getDate(),previousDays=new Date(year,month,0).getDate(),cells=[];$("calendarMonthLabel").textContent=calendarDate.toLocaleDateString("es-AR",{month:"long",year:"numeric"});updateCalendarClock();for(let index=0;index<42;index++){let day,cellDate,outside=false;if(index<offset){day=previousDays-offset+index+1;cellDate=new Date(year,month-1,day);outside=true}else if(index>=offset+days){day=index-offset-days+1;cellDate=new Date(year,month+1,day);outside=true}else{day=index-offset+1;cellDate=new Date(year,month,day)}const key=dateKey(cellDate),today=sameDay(cellDate,new Date()),label=cellDate.toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}),dayEvents=calendarEvents.filter(item=>item.date===key),visible=dayEvents.slice(0,3).map(item=>`<button class="calendar-event" type="button" data-event-id="${item.id}" style="--event-color:${item.color||"#3b82f6"}" title="${escapeHTML(item.title)}"><b>${item.time?escapeHTML(item.time):""}</b><span>${escapeHTML(item.title)}</span></button>`).join(""),more=dayEvents.length>3?`<button class="calendar-more" type="button" data-date="${key}">+${dayEvents.length-3} más</button>`:"";cells.push(`<div class="calendar-day${outside?" outside":""}${today?" today":""}" role="gridcell" data-date="${key}" aria-label="${label}${today?", hoy":""}"${today?' aria-current="date"':""}><div class="calendar-day-head"><span>${day}</span>${today?'<small>Hoy</small>':""}</div><div class="calendar-events">${visible}${more}</div></div>`)}$("calendarGrid").innerHTML=cells.join("")}
function setEventColor(color){selectedEventColor=color;document.querySelectorAll("#calendarEventColors button").forEach(button=>button.classList.toggle("active",button.dataset.color===color))}
function openCalendarModal(date=dateKey(new Date()),item=null){editingCalendarEventId=item?.id||null;$("calendarEventForm").reset();$("calendarFormTitle").textContent=item?"Editar actividad":"Nueva actividad";$("saveCalendarEvent").textContent=item?"Guardar cambios":"Guardar actividad";$("deleteCalendarEvent").classList.toggle("hidden",!item);$("calendarEventTitle").value=item?.title||"";$("calendarEventDate").value=item?.date||date;$("calendarEventTime").value=item?.time||"";$("calendarEventCategory").value=item?.category||"Tarea";$("calendarEventDescription").value=item?.description||"";setEventColor(item?.color||"#3b82f6");updateSelectedDate();$("calendarEventError").classList.add("hidden");$("calendarModal").classList.remove("hidden");document.body.classList.add("modal-open");setTimeout(()=>$("calendarEventTitle").focus(),80)}
function closeCalendarModal(){$("calendarModal").classList.add("closing");document.body.classList.remove("modal-open");setTimeout(()=>{$("calendarModal").classList.add("hidden");$("calendarModal").classList.remove("closing");editingCalendarEventId=null},180)}
function updateSelectedDate(){const value=$("calendarEventDate").value;if(!value)return;const parsed=new Date(`${value}T12:00:00`);$("calendarSelectedDate").textContent=parsed.toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
$("calendarPrevious").addEventListener("click",()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()});
$("calendarNext").addEventListener("click",()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()});
$("calendarToday").addEventListener("click",()=>{calendarDate=new Date(now.getFullYear(),now.getMonth(),1);renderCalendar()});
$("newCalendarEvent").addEventListener("click",()=>openCalendarModal());
$("calendarGrid").addEventListener("click",event=>{const eventButton=event.target.closest("[data-event-id]");if(eventButton){const item=calendarEvents.find(entry=>entry.id===eventButton.dataset.eventId);if(item)openCalendarModal(item.date,item);return}const day=event.target.closest(".calendar-day");if(day)openCalendarModal(day.dataset.date)});
$("calendarEventColors").addEventListener("click",event=>{const button=event.target.closest("button[data-color]");if(button)setEventColor(button.dataset.color)});
$("calendarEventDate").addEventListener("change",updateSelectedDate);[$("closeCalendarModal"),$("cancelCalendarEvent"),$("calendarModalBackdrop")].forEach(button=>button.addEventListener("click",closeCalendarModal));
$("calendarEventForm").addEventListener("submit",async event=>{event.preventDefault();const title=$("calendarEventTitle").value.trim(),date=$("calendarEventDate").value,time=$("calendarEventTime").value,category=$("calendarEventCategory").value,description=$("calendarEventDescription").value.trim();if(!title||!date){$("calendarEventError").textContent="Completa el título y la fecha.";$("calendarEventError").classList.remove("hidden");return}$("saveCalendarEvent").disabled=true;try{const data={title,date,time,category,description,color:selectedEventColor,updatedAt:serverTimestamp()};if(editingCalendarEventId)await update(ref(database,calendarEventPath(editingCalendarEventId)),data);else{const itemRef=push(ref(database,calendarEventPath()));await set(itemRef,{...data,createdAt:serverTimestamp()})}calendarDate=new Date(`${date}T12:00:00`);calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1);closeCalendarModal()}catch(error){console.error(error);$("calendarEventError").textContent="No se pudo guardar la actividad.";$("calendarEventError").classList.remove("hidden")}finally{$("saveCalendarEvent").disabled=false}});
$("deleteCalendarEvent").addEventListener("click",async()=>{if(!editingCalendarEventId||!window.confirm("¿Eliminar esta actividad?"))return;$("deleteCalendarEvent").disabled=true;try{await remove(ref(database,calendarEventPath(editingCalendarEventId)));closeCalendarModal()}finally{$("deleteCalendarEvent").disabled=false}});
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!$("calendarModal").classList.contains("hidden"))closeCalendarModal()});
renderCalendar();
window.setInterval(updateCalendarClock,1000);

function reminderPath(id=""){return `users/${activeUser.uid}/reminders${id?`/${id}`:""}`}
function listenReminders(){onValue(ref(database,reminderPath()),snapshot=>{const data=snapshot.val()||{};reminders=Object.entries(data).map(([id,value])=>({id,...value})).sort((a,b)=>`${a.date||"9999-12-31"} ${a.time||"23:59"}`.localeCompare(`${b.date||"9999-12-31"} ${b.time||"23:59"}`));cleanupReminders();renderReminders()})}
function cleanupReminders(){const limit=Date.now()-RETENTION_MS,toTrash=reminders.filter(item=>item.completed&&!item.deleted&&typeof item.completedAt==="number"&&item.completedAt<=limit),toDelete=reminders.filter(item=>item.deleted&&typeof item.deletedAt==="number"&&item.deletedAt<=limit),legacyTrash=reminders.filter(item=>item.deleted&&typeof item.deletedAt!=="number");const jobs=[...toTrash.map(item=>update(ref(database,reminderPath(item.id)),{deleted:true,deletedAt:serverTimestamp()})),...toDelete.map(item=>remove(ref(database,reminderPath(item.id)))),...legacyTrash.map(item=>update(ref(database,reminderPath(item.id)),{deletedAt:serverTimestamp()}))];if(jobs.length)Promise.all(jobs).catch(error=>console.error("No se pudo completar la limpieza automática de recordatorios.",error))}
function escapeHTML(value=""){const node=document.createElement("div");node.textContent=value;return node.innerHTML}
function parseReminderItems(value){return value.split("\n").filter(line=>line.trim()).slice(0,30).map(line=>{const spaces=line.match(/^[\t ]*/)[0],level=spaces.includes("\t")||spaces.length>=2?1:0,text=line.trim().replace(/^[-•]\s*/,"");return{text,level,done:false}}).filter(item=>item.text)}
function serializeReminderItems(items=[]){return(Array.isArray(items)?items:[]).map(item=>`${item.level?"  ":""}${item.text}`).join("\n")}
function formatReminderDate(date,time){if(!date)return time?`Sin fecha · ${time}`:"Sin fecha ni hora";const parsed=new Date(`${date}T${time||"12:00"}`),today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);let label=parsed.toLocaleDateString("es-AR",{day:"numeric",month:"short"});if(parsed.toDateString()===today.toDateString())label="Hoy";else if(parsed.toDateString()===tomorrow.toDateString())label="Mañana";return `${label}${time?` · ${time}`:""}`}
function isOverdue(item){if(item.completed||!item.date)return false;const end=item.time||"23:59";return new Date(`${item.date}T${end}`)<new Date()}
function renderReminders(){const active=reminders.filter(item=>!item.deleted),trash=reminders.filter(item=>item.deleted),pending=active.filter(item=>!item.completed).length,completed=active.length-pending;$("pendingCount").textContent=pending;$("completedCount").textContent=completed;$("trashCount").textContent=trash.length;if($("welcomePendingCount"))$("welcomePendingCount").textContent=pending;const visible=reminderFilter==="trash"?trash:active.filter(item=>reminderFilter==="all"||(reminderFilter==="completed"?item.completed:!item.completed));$("clearReminders").classList.toggle("hidden",reminderFilter!=="completed"&&reminderFilter!=="trash");$("clearReminders").textContent=reminderFilter==="trash"?"Vaciar papelera":"Borrar completados";$("remindersList").innerHTML=visible.map(item=>{const items=Array.isArray(item.items)?item.items:[],subitems=items.length?`<div class="reminder-subitems">${items.map((sub,index)=>item.deleted?`<div class="subitem level-${sub.level||0} ${sub.done?"done":""}"><span class="sub-check"><i class="fa-solid fa-check"></i></span><span>${escapeHTML(sub.text)}</span></div>`:`<button class="subitem level-${sub.level||0} ${sub.done?"done":""}" data-action="subtoggle" data-id="${item.id}" data-index="${index}"><span class="sub-check"><i class="fa-solid fa-check"></i></span><span>${escapeHTML(sub.text)}</span></button>`).join("")}</div>`:"";return`<article class="reminder-card ${item.completed?"completed":""} ${item.deleted?"deleted":""} ${isOverdue(item)?"overdue":""}">${item.deleted?'<span class="deleted-marker"><i class="fa-regular fa-trash-can"></i></span>':`<button class="complete-reminder" data-action="toggle" data-id="${item.id}" aria-label="${item.completed?"Marcar pendiente":"Marcar completado"}"><i class="fa-solid fa-check"></i></button>`}<div class="reminder-info"><h3>${escapeHTML(item.title)}</h3>${item.description?`<p>${escapeHTML(item.description)}</p>`:""}${subitems}<span class="reminder-date"><i class="fa-regular fa-clock"></i>${isOverdue(item)?"Vencido · ":""}${formatReminderDate(item.date,item.time)}</span></div><div class="reminder-actions">${item.deleted?"":`<button class="edit-reminder" data-action="edit" data-id="${item.id}" aria-label="Editar"><i class="fa-regular fa-pen-to-square"></i></button>`}<button class="delete-reminder ${item.deleted?"restore-reminder":""}" data-action="${item.deleted?"restore":"delete"}" data-id="${item.id}" aria-label="${item.deleted?"Recuperar":"Eliminar"}"><i class="fa-solid ${item.deleted?"fa-rotate-left":"fa-trash-can"}"></i></button></div></article>`}).join("");$("reminderEmpty").classList.toggle("hidden",visible.length>0)}
function toggleForm(show,item=null){const form=$("reminderForm");if(show){editingReminderId=item?.id||null;$("reminderFormTitle").textContent=item?"Editar recordatorio":"Nuevo recordatorio";$("saveReminder").textContent=item?"Guardar cambios":"Guardar recordatorio";$("reminderTitle").value=item?.title||"";$("reminderDate").value=item?.date||"";$("reminderTime").value=item?.time||"";$("reminderDescription").value=item?.description||"";$("reminderItems").value=serializeReminderItems(item?.items);form.classList.add("open");setTimeout(()=>$("reminderTitle").focus(),180)}else{form.classList.remove("open");window.setTimeout(()=>{form.reset();editingReminderId=null;$("reminderError").classList.add("hidden")},330)}}
$("newReminderButton").addEventListener("click",()=>toggleForm(true));$("closeReminderForm").addEventListener("click",()=>toggleForm(false));$("cancelReminder").addEventListener("click",()=>toggleForm(false));
$("reminderForm").addEventListener("submit",async event=>{event.preventDefault();const title=$("reminderTitle").value.trim(),date=$("reminderDate").value,time=$("reminderTime").value,description=$("reminderDescription").value.trim(),parsedItems=parseReminderItems($("reminderItems").value),previous=reminders.find(item=>item.id===editingReminderId),oldItems=Array.isArray(previous?.items)?previous.items:[],items=parsedItems.map((item,index)=>({...item,done:oldItems[index]?.text===item.text&&Number(oldItems[index]?.level||0)===item.level?Boolean(oldItems[index].done):false}));if(!title){$("reminderError").textContent="Escribe un título para el recordatorio.";$("reminderError").classList.remove("hidden");return}$("saveReminder").disabled=true;try{if(editingReminderId)await update(ref(database,reminderPath(editingReminderId)),{title,date,time,description,items,updatedAt:serverTimestamp()});else{const itemRef=push(ref(database,reminderPath()));await set(itemRef,{title,date,time,description,items,completed:false,deleted:false,createdAt:serverTimestamp()})}toggleForm(false)}catch(error){console.error(error);$("reminderError").textContent="No se pudo guardar el recordatorio.";$("reminderError").classList.remove("hidden")}finally{$("saveReminder").disabled=false}});
$("reminderFilters").addEventListener("click",event=>{const button=event.target.closest("button[data-filter]");if(!button)return;document.querySelector(".reminder-filters .active")?.classList.remove("active");button.classList.add("active");reminderFilter=button.dataset.filter;renderReminders()});
$("remindersList").addEventListener("click",async event=>{const button=event.target.closest("button[data-action]");if(!button)return;const item=reminders.find(reminder=>reminder.id===button.dataset.id);if(!item)return;if(button.dataset.action==="edit")toggleForm(true,item);else if(button.dataset.action==="toggle")await update(ref(database,reminderPath(item.id)),{completed:!item.completed,completedAt:!item.completed?serverTimestamp():null});else if(button.dataset.action==="delete")await update(ref(database,reminderPath(item.id)),{deleted:true,deletedAt:serverTimestamp()});else if(button.dataset.action==="restore")await update(ref(database,reminderPath(item.id)),{deleted:false,deletedAt:null,completed:false,completedAt:null});else if(button.dataset.action==="subtoggle"){const index=Number(button.dataset.index),items=Array.isArray(item.items)?item.items:[];if(items[index])await update(ref(database,`${reminderPath(item.id)}/items/${index}`),{done:!items[index].done})}})
$("clearReminders").addEventListener("click",async()=>{const targets=reminders.filter(item=>reminderFilter==="trash"?item.deleted:item.completed&&!item.deleted);if(!targets.length)return;const message=reminderFilter==="trash"?"¿Vaciar la papelera definitivamente?":"¿Borrar definitivamente todos los completados?";if(!window.confirm(message))return;$("clearReminders").disabled=true;try{await Promise.all(targets.map(item=>remove(ref(database,reminderPath(item.id)))))}finally{$("clearReminders").disabled=false}})


/* =========================
   ARCHIVOS / DRIVE PERSONAL
   ========================= */
const MAX_FILE_SIZE=25*1024*1024;
function drivePath(id=""){return `users/${activeUser.uid}/driveItems${id?`/${id}`:""}`}
function normalizeParentId(value){return value&&value!=="root"?value:null}
function listenDriveItems(){onValue(ref(database,drivePath()),snapshot=>{const data=snapshot.val()||{};driveItems=Object.entries(data).map(([id,value])=>({id,...value}));if(currentFolderId&&!driveItems.some(item=>item.id===currentFolderId&&item.type==="folder"))currentFolderId=null;renderDriveItems()})}
function getDriveItem(id){return driveItems.find(item=>item.id===id)}
function childItems(parentId=currentFolderId){const normalized=normalizeParentId(parentId);return driveItems.filter(item=>normalizeParentId(item.parentId)===normalized)}
function folderPathIds(folderId){const ids=[];let current=folderId,guard=0;while(current&&guard++<100){const item=getDriveItem(current);if(!item||item.type!=="folder")break;ids.unshift(item.id);current=normalizeParentId(item.parentId)}return ids}
function folderPathLabel(folderId){const names=folderPathIds(folderId).map(id=>getDriveItem(id)?.name).filter(Boolean);return names.length?`Inicio / ${names.join(" / ")}`:"Inicio"}
function fileExtension(name=""){const match=name.toLowerCase().match(/\.([a-z0-9]+)$/);return match?match[1]:""}
function fileKind(name=""){const ext=fileExtension(name);if(ext==="pdf")return"pdf";if(ext==="docx")return"word";return""}
function fileBaseName(name=""){const ext=fileExtension(name);return ext?name.slice(0,-ext.length-1):name}
function safeFileName(name=""){return name.replace(/[\\/:*?"<>|#%{}]/g,"-").replace(/\s+/g," ").trim().slice(0,120)||"documento"}
function formatFileSize(bytes=0){if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(bytes<10*1024?1:0)} KB`;return`${(bytes/(1024*1024)).toFixed(bytes<10*1024*1024?1:0)} MB`}
function formatDriveDate(value){if(!value||typeof value!=="number")return"Ahora";return new Date(value).toLocaleDateString("es-AR",{day:"2-digit",month:"short",year:"numeric"})}
function escapeAttr(value=""){return escapeHTML(value).replace(/"/g,"&quot;")}
function renderBreadcrumbs(){const root=`<button type="button" data-folder-id="root"><i class="fa-solid fa-house"></i><span>Archivos</span></button>`;const crumbs=folderPathIds(currentFolderId).map((id,index,array)=>{const folder=getDriveItem(id);return`<i class="fa-solid fa-chevron-right"></i><button type="button" data-folder-id="${id}" ${index===array.length-1?'class="current"':''}>${escapeHTML(folder?.name||"Carpeta")}</button>`}).join("");$("filesBreadcrumbs").innerHTML=root+crumbs}
function renderDriveItems(){if(!$("filesGrid"))return;renderBreadcrumbs();const query=$("filesSearch")?.value.trim().toLowerCase()||"";const visible=childItems().filter(item=>!query||String(item.name||"").toLowerCase().includes(query)).sort((a,b)=>a.type===b.type?String(a.name||"").localeCompare(String(b.name||""),"es",{sensitivity:"base"}):a.type==="folder"?-1:1);$("filesGrid").classList.toggle("list-mode",filesViewMode==="list");$("filesGrid").innerHTML=visible.map(item=>item.type==="folder"?renderFolderCard(item):renderFileCard(item)).join("");$("filesEmpty").classList.toggle("hidden",visible.length>0||Boolean(query));if(query&&visible.length===0){$("filesEmpty").classList.remove("hidden");$("filesEmpty").querySelector("h2").textContent="Sin resultados";$("filesEmpty").querySelector("p").textContent="No encontramos elementos con ese nombre en esta carpeta.";$("filesEmpty").querySelector("div").classList.add("hidden")}else{$("filesEmpty").querySelector("h2").textContent="Esta carpeta está vacía";$("filesEmpty").querySelector("p").textContent="Creá una carpeta o subí un documento para empezar.";$("filesEmpty").querySelector("div").classList.remove("hidden")}}
function renderFolderCard(item){const count=childItems(item.id).length;return`<article class="drive-card folder-card" data-id="${item.id}" data-type="folder"><button class="drive-card-main" type="button" data-drive-action="open-folder" data-id="${item.id}"><span class="drive-icon folder"><i class="fa-solid fa-folder"></i></span><span class="drive-info"><strong>${escapeHTML(item.name)}</strong><small>${count} ${count===1?"elemento":"elementos"} · ${formatDriveDate(item.updatedAt||item.createdAt)}</small></span></button><div class="drive-actions"><button type="button" data-drive-action="edit" data-id="${item.id}" aria-label="Editar carpeta"><i class="fa-regular fa-pen-to-square"></i></button><button class="danger" type="button" data-drive-action="delete" data-id="${item.id}" aria-label="Eliminar carpeta"><i class="fa-regular fa-trash-can"></i></button></div></article>`}
function renderFileCard(item){const isPdf=item.fileType==="pdf",ext=(item.extension||fileExtension(item.name)).toUpperCase(),canEditContent=isPdf||item.extension==="docx";return`<article class="drive-card file-card" data-id="${item.id}" data-type="file"><button class="drive-card-main" type="button" data-drive-action="open-file" data-id="${item.id}"><span class="drive-icon ${isPdf?"pdf":"word"}"><i class="fa-solid ${isPdf?"fa-file-pdf":"fa-file-word"}"></i></span><span class="drive-info"><strong>${escapeHTML(item.name)}</strong><small>${ext} · ${formatFileSize(Number(item.size)||0)} · ${formatDriveDate(item.updatedAt||item.createdAt)}</small></span></button><div class="drive-actions">${canEditContent?`<button type="button" data-drive-action="edit-content" data-id="${item.id}" aria-label="Editar contenido"><i class="fa-solid fa-pen"></i></button>`:""}<button type="button" data-drive-action="edit" data-id="${item.id}" aria-label="Cambiar nombre o ubicación"><i class="fa-solid fa-sliders"></i></button><button type="button" data-drive-action="download" data-id="${item.id}" aria-label="Descargar archivo"><i class="fa-solid fa-arrow-down"></i></button><button class="danger" type="button" data-drive-action="delete" data-id="${item.id}" aria-label="Eliminar archivo"><i class="fa-regular fa-trash-can"></i></button></div></article>`}
function openFilesModal(id){$(id).classList.remove("hidden");document.body.classList.add("modal-open")}
function closeFilesModal(id){$(id).classList.add("hidden");if(document.querySelectorAll(".files-modal:not(.hidden)").length===0)document.body.classList.remove("modal-open")}
function openNewFolderModal(){$("folderForm").reset();$("folderError").classList.add("hidden");openFilesModal("folderModal");setTimeout(()=>$('folderName').focus(),80)}
function descendantFolderIds(folderId){const result=new Set(),walk=id=>{driveItems.filter(item=>item.type==="folder"&&normalizeParentId(item.parentId)===id).forEach(folder=>{if(!result.has(folder.id)){result.add(folder.id);walk(folder.id)}})};walk(folderId);return result}
function buildFolderOptions(item){const blocked=item?.type==="folder"?descendantFolderIds(item.id):new Set();if(item?.type==="folder")blocked.add(item.id);const folders=driveItems.filter(folder=>folder.type==="folder"&&!blocked.has(folder.id)).sort((a,b)=>folderPathLabel(a.id).localeCompare(folderPathLabel(b.id),"es"));return[`<option value="root">Archivos</option>`,...folders.map(folder=>`<option value="${folder.id}">${escapeHTML(folderPathLabel(folder.id))}</option>`)].join("")}
function openEditDriveItem(item){editingDriveItemId=item.id;$("editItemModalTitle").textContent=item.type==="folder"?"Editar carpeta":"Editar archivo";$("editItemName").value=item.type==="file"?fileBaseName(item.name):item.name;$("editItemParent").innerHTML=buildFolderOptions(item);$("editItemParent").value=normalizeParentId(item.parentId)||"root";$("editItemHelp").textContent=item.type==="file"?`Podés cambiar el nombre o mover el ${item.fileType==="pdf"?"PDF":"documento de Word"} a otra carpeta.`:"Podés renombrar o mover esta carpeta.";$("editItemError").classList.add("hidden");openFilesModal("editItemModal");setTimeout(()=>$('editItemName').focus(),80)}
async function createFolder(name){const itemRef=push(ref(database,drivePath()));await set(itemRef,{type:"folder",name,parentId:currentFolderId||null,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
function canonicalFileType(kind){return kind==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
function uploadDocument(file,targetRef,contentType){return new Promise((resolve,reject)=>{const task=uploadBytesResumable(targetRef,file,{contentType}),STALL_MS=45000;let stallTimer;const resetStallTimer=()=>{clearTimeout(stallTimer);stallTimer=setTimeout(()=>{const error=new Error("La carga se detuvo por falta de conexión.");error.code="storage/upload-stalled";reject(error);task.cancel()},STALL_MS)};resetStallTimer();task.on("state_changed",snapshot=>{resetStallTimer();const progress=snapshot.totalBytes?Math.round(snapshot.bytesTransferred/snapshot.totalBytes*100):0;showUploadToast(file.name,`Subiendo documento... ${progress}%`)},error=>{clearTimeout(stallTimer);reject(error)},()=>{clearTimeout(stallTimer);resolve(task.snapshot.ref)})})}
function limitWait(promise,timeout=30000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{const error=new Error("La operación tardó demasiado.");error.code="storage/operation-stalled";reject(error)},timeout);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})})}
function uploadErrorMessage(error){if(error?.code==="storage/unauthorized")return"Firebase rechazó la carga. Publicá las reglas incluidas en storage.rules.";if(error?.code==="storage/upload-stalled"||error?.code==="storage/operation-stalled"||error?.code==="storage/retry-limit-exceeded"||error?.code==="storage/canceled")return"La carga se detuvo. Revisá tu conexión e intentá nuevamente.";return"No se pudo subir el documento. Revisá Firebase Storage e intentá nuevamente."}
async function uploadFiles(fileList){const files=Array.from(fileList||[]);if(!files.length)return;$("uploadFileButton").disabled=true;try{for(const file of files){const kind=fileKind(file.name);if(!kind){window.alert(`“${file.name}” no se subió. Solo se permiten archivos Word y PDF.`);continue}if(file.size>MAX_FILE_SIZE){window.alert(`“${file.name}” supera el límite de 25 MB.`);continue}const itemRef=push(ref(database,drivePath())),id=itemRef.key,clean=safeFileName(file.name),path=`users/${activeUser.uid}/files/${id}/${clean}`,fileRef=storageRef(storage,path),contentType=canonicalFileType(kind);showUploadToast(file.name,"Preparando documento... 0%");try{const uploadedRef=await uploadDocument(file,fileRef,contentType),downloadURL=await limitWait(getDownloadURL(uploadedRef));showUploadToast(file.name,"Guardando en Archivos...");await limitWait(set(itemRef,{type:"file",name:clean,parentId:currentFolderId||null,fileType:kind,extension:fileExtension(clean),size:file.size,mimeType:contentType,storagePath:path,downloadURL,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));showUploadToast(file.name,"Listo",true)}catch(error){console.error(error);try{await deleteObject(fileRef)}catch(cleanupError){if(cleanupError?.code!=="storage/object-not-found")console.error(cleanupError)}showUploadToast(file.name,uploadErrorMessage(error),false,true)}}}finally{$("uploadFileButton").disabled=false;$("fileUploadInput").value=""}}
function showUploadToast(name,status,done=false,error=false){clearTimeout(showUploadToast.timer);$("filesUploadToast").classList.remove("hidden");$("filesUploadToast").classList.toggle("done",done);$("filesUploadToast").classList.toggle("error",error);$("filesUploadTitle").textContent=done?"Archivo subido":error?"No se pudo subir":name;$("filesUploadStatus").textContent=status;if(done||error)showUploadToast.timer=setTimeout(hideUploadToast,error?5000:1800)}
function hideUploadToast(){clearTimeout(showUploadToast.timer);$("filesUploadToast").classList.add("hidden");$("filesUploadToast").classList.remove("done","error")}
async function openDriveFile(item,download=false){try{const url=item.downloadURL||await getDownloadURL(storageRef(storage,item.storagePath));if(download){const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener";a.download=item.name;document.body.appendChild(a);a.click();a.remove()}else window.open(url,"_blank","noopener") }catch(error){console.error(error);window.alert("No se pudo abrir el archivo.")}}
async function deleteDriveFile(item){if(item.storagePath){try{await deleteObject(storageRef(storage,item.storagePath))}catch(error){if(error?.code!=="storage/object-not-found")console.error(error)}}await remove(ref(database,drivePath(item.id)))}
async function deleteDriveItem(item){if(item.type==="file"){if(!window.confirm(`¿Eliminar “${item.name}”?`))return;await deleteDriveFile(item);return}const descendants=descendantFolderIds(item.id),allFolderIds=new Set([item.id,...descendants]),files=driveItems.filter(child=>child.type==="file"&&allFolderIds.has(normalizeParentId(child.parentId))),folders=driveItems.filter(child=>child.type==="folder"&&allFolderIds.has(child.id));if(!window.confirm(`¿Eliminar la carpeta “${item.name}”${files.length||folders.length>1?" y todo su contenido":""}?`))return;for(const file of files)await deleteDriveFile(file);await Promise.all(folders.map(folder=>remove(ref(database,drivePath(folder.id)))))}
$("newFolderButton").addEventListener("click",openNewFolderModal);$("uploadFileButton").addEventListener("click",()=>$("fileUploadInput").click());$("fileUploadInput").addEventListener("change",event=>uploadFiles(event.target.files));
$("folderForm").addEventListener("submit",async event=>{event.preventDefault();const name=$("folderName").value.trim();if(!name){$("folderError").textContent="Escribí un nombre para la carpeta.";$("folderError").classList.remove("hidden");return}const duplicate=childItems().some(item=>item.type==="folder"&&item.name.toLowerCase()===name.toLowerCase());if(duplicate){$("folderError").textContent="Ya existe una carpeta con ese nombre acá.";$("folderError").classList.remove("hidden");return}$("saveFolderButton").disabled=true;try{await createFolder(name);closeFilesModal("folderModal")}catch(error){console.error(error);$("folderError").textContent="No se pudo crear la carpeta.";$("folderError").classList.remove("hidden")}finally{$("saveFolderButton").disabled=false}})
$("editItemForm").addEventListener("submit",async event=>{event.preventDefault();const item=getDriveItem(editingDriveItemId);if(!item)return;const base=$("editItemName").value.trim(),parentId=normalizeParentId($("editItemParent").value);if(!base){$("editItemError").textContent="El nombre no puede quedar vacío.";$("editItemError").classList.remove("hidden");return}const finalName=item.type==="file"?`${safeFileName(fileBaseName(base))}.${item.extension||fileExtension(item.name)}`:safeFileName(base);const duplicate=driveItems.some(other=>other.id!==item.id&&normalizeParentId(other.parentId)===parentId&&other.type===item.type&&String(other.name).toLowerCase()===finalName.toLowerCase());if(duplicate){$("editItemError").textContent="Ya existe un elemento con ese nombre en esa ubicación.";$("editItemError").classList.remove("hidden");return}$("saveEditItemButton").disabled=true;try{await update(ref(database,drivePath(item.id)),{name:finalName,parentId:parentId||null,updatedAt:serverTimestamp()});closeFilesModal("editItemModal")}catch(error){console.error(error);$("editItemError").textContent="No se pudieron guardar los cambios.";$("editItemError").classList.remove("hidden")}finally{$("saveEditItemButton").disabled=false}})
document.querySelectorAll("[data-close-files-modal]").forEach(button=>button.addEventListener("click",()=>closeFilesModal(button.dataset.closeFilesModal)));
$("filesBreadcrumbs").addEventListener("click",event=>{const button=event.target.closest("button[data-folder-id]");if(!button)return;currentFolderId=button.dataset.folderId==="root"?null:button.dataset.folderId;$("filesSearch").value="";renderDriveItems()});
$("filesGrid").addEventListener("click",async event=>{const button=event.target.closest("[data-drive-action]");if(!button)return;const item=getDriveItem(button.dataset.id);if(!item)return;const action=button.dataset.driveAction;if(action==="open-folder"){currentFolderId=item.id;$("filesSearch").value="";renderDriveItems()}else if(action==="open-file")await openDriveFile(item);else if(action==="edit-content")await openFileContentEditor(item);else if(action==="download")await openDriveFile(item,true);else if(action==="edit")openEditDriveItem(item);else if(action==="delete")await deleteDriveItem(item)});
$("filesSearch").addEventListener("input",renderDriveItems);$("filesGridToggle").addEventListener("click",()=>{filesViewMode="grid";$("filesGridToggle").classList.add("active");$("filesListToggle").classList.remove("active");renderDriveItems()});$("filesListToggle").addEventListener("click",()=>{filesViewMode="list";$("filesListToggle").classList.add("active");$("filesGridToggle").classList.remove("active");renderDriveItems()});
$("filesEmpty").addEventListener("click",event=>{const action=event.target.closest("[data-files-action]")?.dataset.filesAction;if(action==="new-folder")openNewFolderModal();else if(action==="upload")$("fileUploadInput").click()});
const dropZone=$("filesDropZone");["dragenter","dragover"].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.add("dragging")}));["dragleave","drop"].forEach(type=>dropZone.addEventListener(type,event=>{event.preventDefault();dropZone.classList.remove("dragging")}));dropZone.addEventListener("drop",event=>uploadFiles(event.dataTransfer.files));


/* Editor básico de contenido para Word (.docx) y PDF */
function setFileEditorLoading(loading){$("fileEditorLoading").classList.toggle("hidden",!loading);$("docxEditorWrap").classList.add("hidden");$("pdfEditorWrap").classList.add("hidden");$("saveFileContentButton").disabled=loading}
function closeFileContentEditor(){editingFileContentId=null;pdfPendingAnnotations=[];$("fileEditorModal").classList.add("hidden");$("docxEditor").innerHTML="";$("pdfPreviewFrame").src="about:blank";$("fileEditorError").classList.add("hidden");document.body.classList.remove("modal-open")}
async function fetchDriveBlob(item){const url=item.downloadURL||await getDownloadURL(storageRef(storage,item.storagePath)),response=await fetch(url);if(!response.ok)throw new Error("No se pudo descargar el archivo");return await response.blob()}
async function openFileContentEditor(item){if(item.type!=="file")return;if(item.fileType!=="pdf"&&item.extension!=="docx"){window.alert("La edición de contenido está disponible para PDF y Word .docx.");return}editingFileContentId=item.id;pdfPendingAnnotations=[];$("fileEditorTitle").textContent=item.name;$("fileEditorType").textContent=item.fileType==="pdf"?"PDF":"WORD";$("fileEditorSubtitle").textContent=item.fileType==="pdf"?"Agregá texto y guardá una nueva versión sobre el mismo archivo.":"Editá texto y formato básico directamente desde el Hub.";$("fileEditorError").classList.add("hidden");$("fileEditorModal").classList.remove("hidden");document.body.classList.add("modal-open");setFileEditorLoading(true);try{const blob=await fetchDriveBlob(item);if(item.fileType==="pdf"){const url=URL.createObjectURL(blob);$("pdfPreviewFrame").src=url;$("pdfPreviewFrame").dataset.objectUrl=url;const bytes=await blob.arrayBuffer(),pdfDoc=await PDFLib.PDFDocument.load(bytes);$("pdfAnnotationPage").max=String(pdfDoc.getPageCount());$("pdfAnnotationPage").value="1";$("pdfEditorWrap").classList.remove("hidden");renderPdfAnnotations()}else{if(!window.mammoth)throw new Error("No se cargó el editor de Word");const result=await window.mammoth.convertToHtml({arrayBuffer:await blob.arrayBuffer()});$("docxEditor").innerHTML=result.value||"<p></p>";$("docxEditorWrap").classList.remove("hidden")}}catch(error){console.error(error);$("fileEditorError").textContent="No se pudo cargar el editor de este archivo.";$("fileEditorError").classList.remove("hidden")}finally{$("fileEditorLoading").classList.add("hidden");$("saveFileContentButton").disabled=false}}
function renderPdfAnnotations(){$("pdfAnnotations").innerHTML=pdfPendingAnnotations.length?pdfPendingAnnotations.map((annotation,index)=>`<div class="pdf-annotation-chip"><span><b>Pág. ${annotation.page}</b>${escapeHTML(annotation.text)}</span><button type="button" data-remove-pdf-annotation="${index}" aria-label="Quitar"><i class="fa-solid fa-xmark"></i></button></div>`).join(""):'<p class="pdf-no-annotations">Todavía no agregaste texto.</p>'}
function wrapPdfText(text,font,size,maxWidth){const words=String(text).replace(/\s+/g," ").trim().split(" "),lines=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=maxWidth)line=test;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines}
async function saveDocxContent(item){if(!window.htmlDocx)throw new Error("No se cargó el generador de Word");const html=`<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;line-height:1.5}p{margin:0 0 8pt}ul,ol{margin:0 0 8pt 18pt}</style></head><body>${$("docxEditor").innerHTML}</body></html>`,blob=window.htmlDocx.asBlob(html);await uploadBytes(storageRef(storage,item.storagePath),blob,{contentType:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"});const downloadURL=await getDownloadURL(storageRef(storage,item.storagePath));await update(ref(database,drivePath(item.id)),{size:blob.size,downloadURL,updatedAt:serverTimestamp()})}
async function savePdfContent(item){if(!pdfPendingAnnotations.length)return;const original=await fetchDriveBlob(item),pdfDoc=await PDFLib.PDFDocument.load(await original.arrayBuffer()),font=await pdfDoc.embedFont(PDFLib.StandardFonts.Helvetica);for(const [index,annotation] of pdfPendingAnnotations.entries()){const page=pdfDoc.getPage(Math.min(Math.max(annotation.page-1,0),pdfDoc.getPageCount()-1)),{width,height}=page.getSize(),size=annotation.size,maxWidth=Math.max(120,width-90),lines=wrapPdfText(annotation.text,font,size,maxWidth),blockHeight=lines.length*(size+4);let y=annotation.position==="bottom"?45:annotation.position==="center"?(height-blockHeight)/2:height-55;for(const line of lines){page.drawText(line,{x:45,y,size,font,color:PDFLib.rgb(.12,.13,.12),maxWidth});y-=size+4}}const bytes=await pdfDoc.save(),blob=new Blob([bytes],{type:"application/pdf"});await uploadBytes(storageRef(storage,item.storagePath),blob,{contentType:"application/pdf"});const downloadURL=await getDownloadURL(storageRef(storage,item.storagePath));await update(ref(database,drivePath(item.id)),{size:blob.size,downloadURL,updatedAt:serverTimestamp()})}
$("fileEditorDownload").addEventListener("click",()=>{const item=getDriveItem(editingFileContentId);if(item)openDriveFile(item,true)});document.querySelectorAll("[data-close-file-editor]").forEach(button=>button.addEventListener("click",closeFileContentEditor));document.querySelectorAll("[data-doc-command]").forEach(button=>button.addEventListener("click",()=>{document.execCommand(button.dataset.docCommand,false,null);$("docxEditor").focus()}));
$("pdfAddAnnotation").addEventListener("click",()=>{const text=$("pdfAnnotationText").value.trim(),page=Number($("pdfAnnotationPage").value),size=Number($("pdfAnnotationSize").value),maxPage=Number($("pdfAnnotationPage").max)||1;if(!text)return;if(!Number.isFinite(page)||page<1||page>maxPage){window.alert(`Elegí una página entre 1 y ${maxPage}.`);return}pdfPendingAnnotations.push({text,page,size:Math.min(32,Math.max(8,size||12)),position:$("pdfAnnotationPosition").value});$("pdfAnnotationText").value="";renderPdfAnnotations()});$("pdfAnnotations").addEventListener("click",event=>{const button=event.target.closest("[data-remove-pdf-annotation]");if(!button)return;pdfPendingAnnotations.splice(Number(button.dataset.removePdfAnnotation),1);renderPdfAnnotations()});
$("saveFileContentButton").addEventListener("click",async()=>{const item=getDriveItem(editingFileContentId);if(!item)return;$("saveFileContentButton").disabled=true;$("saveFileContentButton").textContent="Guardando...";$("fileEditorError").classList.add("hidden");try{if(item.fileType==="pdf")await savePdfContent(item);else await saveDocxContent(item);closeFileContentEditor();showUploadToast(item.name,"Cambios guardados",true)}catch(error){console.error(error);$("fileEditorError").textContent="No se pudieron guardar los cambios del documento.";$("fileEditorError").classList.remove("hidden")}finally{$("saveFileContentButton").disabled=false;$("saveFileContentButton").textContent="Guardar cambios"}})
